site_name: TC Learning
theme:
  # language: zh
  name: readthedocs
# extra:
#   alternate:
#     - name: English
#       link: /en/ 
#       lang: en
#     - name: 中文
#       link: /zh/
#       lang: zh
# site_name:
#   en: My Documentation
#   zh: 我的文档
plugins:
  - search:
      prebuild_index: true  # 预构建索引
# copyright: Copyright &copy; Technical Communication Society in CQUPT # 左下角的版权声明
nav:
  - Welcome: index.md
  - PATH TO A TCER: 
    - Introduction: path-to-a-tcer/introduction.md
    - Skills: path-to-a-tcer/skills.md
    - Tools: path-to-a-tcer/tools.md
# mkdocs.yml
remote_branch: gh-pages    # GitHub Pages 分支
remote_name: tc_learning_path       # 远程仓库名
# mkdocs.yml
site_url: https://tccqupt.github.io/tc_learning_path/
repo_url: https://github.com/TCCQUPT/tc_learning_path
edit_uri: edit/main/docs/
