site_name: TC Learning
theme:
  # language: zh
  name: readthedocs
# extra:
#   alternate:
#     - name: English
#       link: /en/ 
#       lang: en
#     - name: 中文
#       link: /zh/
#       lang: zh
# site_name:
#   en: My Documentation
#   zh: 我的文档
plugins:
  - search:
      prebuild_index: true  # 预构建索引
# copyright: Copyright &copy; Technical Communication Society in CQUPT # 左下角的版权声明
nav:
  - Welcome: index.md
  - Prerequisites: prerequisites.md
  - Introduction: introduction.md
  - git-and-github : 
      - What is Git&GitHub: ./git-and-github/basics.md
      - Why to use: ./git-and-github/collaboration.md
      - How to use: ./git-and-github/commands.md
  - markdown:
      - What is Markdown: intro.md
      - How to use: formatting.md
      - Why to use: examples.md
  - mkdocs:
      - What is MkDocs: intro.md
      - How to use: setup.md
      - Customization: customization.md
  - workflow:
      - Doc-like-code: doc-like-code.md
      - Example: example-workflow.md
      - Practice: best-practice.md
  - Resources: resources.md    
# mkdocs.yml
remote_branch: gh-pages    # GitHub Pages 分支
remote_name: origin       # 远程仓库名
# mkdocs.yml
site_url: https://tccqupt.github.io/tc_learning_path/
repo_url: https://github.com/TCCQUPT/tc_learning_path
edit_uri: edit/main/docs/
