name: Assign Issue on Comment

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  assign-issue:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.comment.body, '@assign') &&
      github.event.issue.state == 'open'

    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Set up Git Config
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"

      - name: Try to assign issue to commenter
        id: assign_issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ASSIGNEE: ${{ github.event.comment.user.login }}
        run: |
          set +e  # disable immediate exit on error

          # Try to assign
          gh issue edit "$ISSUE_NUMBER" --add-assignee "$ASSIGNEE"

          if [ $? -eq 0 ]; then
            echo "::set-output name=success::true"
            echo "✅ Successfully assigned to @$ASSIGNEE"
          else
            echo "::set-output name=success::false"
            echo "❌ Failed to assign to @$ASSIGNEE"
          fi

      - name: Reply with warning message if failed
        if: steps.assign_issue.outputs.success == 'false'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}     # ✅ 必须添加
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ASSIGNEE: ${{ github.event.comment.user.login }}
        run: |
          gh issue comment "$ISSUE_NUMBER" --body="⚠️ Hi @$ASSIGNEE, you cannot be assigned to this issue because you are not a collaborator on this repository. Please contact an administrator to request access."
