name: Assign Issue on Comment

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  contents: read

jobs:
  assign-issue:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '@assign')
    steps:
      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Assign issue to commenter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ASSIGNEE: ${{ github.event.comment.user.login }}
          REPO: ${{ github.repository }}
        run: |
          # Directly try to assign the issue and capture the result
          if gh issue edit "$ISSUE_NUMBER" --repo "$REPO" --add-assignee "$ASSIGNEE"; then
            echo "Issue #$ISSUE_NUMBER successfully assigned to $ASSIGNEE"
          else
            gh issue comment "$ISSUE_NUMBER" --repo "$REPO" --body "⚠️ There was a problem assigning @$ASSIGNEE to this issue. Please check if you have sufficient permissions."
            exit 1
          fi
